services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/home/app/code:rw
    command: dev
    depends_on:
      - redis
      - celery
    networks:
      ntwrk:
        aliases:
          - backend
          - api.backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./frontend/src:/code/src:rw
      - node_modules:/code/node_modules:rw
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ntwrk
  
  redis:
    image: redis:alpine
  
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./backend:/home/app/code:rw
    command: celery
    depends_on:
      - redis
    networks:
      - ntwrk

volumes:
  node_modules:

networks:
  ntwrk:
