services:
  backend:
    container_name: backend
    image: ${DOCKERHUB_USERNAME}/${REPO_NAME}-backend:latest
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/app/code/logs:rw
      - ./static:/home/app/code/static:rw
      - ./media:/home/app/code/media:rw
    ports:
      - "8000:8000"
    command: prod
    depends_on:
      - redis
      - celery
  
  frontend:
    container_name: frontend
    image: ${DOCKERHUB_USERNAME}/${REPO_NAME}-frontend:latest
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    container_name: redis
    image: redis:alpine
  
  celery:
    container_name: celery
    image: ${DOCKERHUB_USERNAME}/${REPO_NAME}-backend:latest
    env_file:
      - ./.env
    command: celery
    depends_on:
      - redis