services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/home/app/code:rw
    command: dev
    networks:
      ntwrk:
        aliases:
          - backend
          - api.backend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      NEXT_TURBOPACK_TRACING: 1
    volumes:
      - ./frontend/src:/code/src:rw
      - /code/node_modules
    ports:
      - "3000:3000"
    networks:
      - ntwrk

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - ntwrk

  celery:
    container_name: celery
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./backend:/home/app/code:rw
    command: celery
    depends_on:
      - redis
    networks:
      - ntwrk

networks:
  ntwrk:
