services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/home/app/code:rw
    command: dev
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./frontend:/code:rw
    ports:
      - "3000:3000"
    depends_on:
      - backend
